version: '3.4'

services:
  weatherapi:
    image: ${DOCKER_REGISTRY-}weatherapi
    build:
      context: .
      dockerfile: weatherApi/Dockerfile
  web-ui:
    image: web-ui
    build:
      context: web-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
